---
# roles/prestashop/tasks/mysql.yml

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes
  tags: mysql

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  tags: mysql

- name: Install MySQL Python client
  apt:
    name: python3-pymysql
    state: present
  become: yes
  tags: mysql

# Create dedicated PrestaShop database (no admin user needed)
- name: Create PrestaShop database
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: |
      CREATE DATABASE IF NOT EXISTS {{ prestashop_db_name }}
      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  become: yes
  tags: database

- name: Create application user with limited privileges
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: |
      CREATE USER IF NOT EXISTS '{{ prestashop_db_user }}'@'localhost'
      IDENTIFIED BY '{{ prestashop_db_password }}';
      
      GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP,
      REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
      CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE
      ON {{ prestashop_db_name }}.*
      TO '{{ prestashop_db_user }}'@'localhost';
      
      FLUSH PRIVILEGES;
  become: yes
  tags: database

# Optional security hardening
- name: Remove insecure defaults
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: |
      DELETE FROM mysql.user WHERE User = '';
      DROP DATABASE IF EXISTS test;
      FLUSH PRIVILEGES;
  become: yes
  tags: mysql