---
# roles/prestashop/tasks/mysql.yml

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes
  tags: mysql

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  tags: mysql

- name: Install MySQL Python client
  apt:
    name: python3-pymysql
    state: present
  become: yes
  tags: mysql

# Critical change for modern MySQL installations
- name: Configure root authentication
  block:
    - name: Check if root has password
      command: mysql -u root -e "SELECT 1"
      register: root_access
      ignore_errors: yes
      changed_when: false
      become: yes

    - name: Set root password (when no password exists)
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        password: "{{ prestashop_mysql_root_password }}"
        host: localhost
        plugin: mysql_native_password
        state: present
      when: root_access.rc != 0
      no_log: true
      become: yes

    - name: Update root password (when password exists)
      mysql_user:
        login_user: root
        login_password: "{{ prestashop_mysql_root_password }}"
        name: root
        password: "{{ prestashop_mysql_root_password }}"
        host: localhost
        state: present
      when: root_access.rc == 0
      no_log: true
      become: yes
  tags: mysql

- name: Remove insecure defaults
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ""
    host: localhost
    state: absent
  no_log: true
  become: yes
  tags: mysql

- name: Remove test database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: test
    state: absent
  no_log: true
  become: yes
  tags: mysql

- name: Create PrestaShop database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ prestashop_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
  no_log: true
  become: yes
  tags: database

- name: Create application database user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ prestashop_admin_db_user }}"
    password: "{{ prestashop_admin_db_password }}"
    host: "%"
    priv: "{{ prestashop_db_name }}.*:ALL,GRANT"
    state: present
  no_log: true
  become: yes
  tags: database

- name: Apply privilege changes
  mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "FLUSH PRIVILEGES"
  no_log: true
  become: yes
  tags: database