---
# roles/prestashop/tasks/mysql.yml

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: yes
  tags: mysql

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  tags: mysql

- name: Install MySQL Python client
  apt:
    name: python3-pymysql
    state: present
  become: yes
  tags: mysql

- name: Set root password and remove anonymous users
  mysql_secure_installation:
    login_user: root
    login_password: ''
    root_password: "{{ mysql_root_password }}"
    remove_anonymous_user: yes
    disallow_root_login_remotely: yes
    remove_test_database: yes
    state: present

- name: Create PrestaShop database
  mysql_db:
    name: "{{ prestashop_db_name }}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- name: Create PrestaShop DB user
  mysql_user:
    name: "{{ prestashop_db_user }}"
    password: "{{ prestashop_db_password }}"
    priv: "{{ prestashop_db_name }}.*:ALL"
    host: localhost
    state: present