---

- name: Install PHP and required modules
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-zip
      - unzip
    state: present  
