---

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Add PHP 8.1 PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes


- name: Install PHP8.1 and extensions
  apt:
    name:
      - php8.1
      - php8.1-mysql
      - libapache2-mod-php8.1
      - php8.1-cli
      - php8.1-curl
      - php8.1-gd
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-zip
      - php8.1-intl
      - php8.1-common
      - php8.1-soap
      - php8.1-bcmath
      - php8.1-opcache
      - php8.1-dom
      - unzip
    state: present  
    update_cache: yes
