---
- name: Install unzip and curl
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download PrestaShop 8.1.4
  get_url:
    url: https://github.com/PrestaShop/PrestaShop/releases/download/8.1.4/prestashop_8.1.4.zip
    dest: /tmp/prestashop.zip

- name: Unzip PrestaShop into web root
  unarchive:
    src: /tmp/prestashop.zip
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [ '-o' ]

- name: Set permissions on web root
  file:
    path: /var/www/html
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'


- name: Remove Apache default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Move PrestaShop contents from subfolder if it exists
  command: >
    mv /var/www/html/prestashop/* /var/www/html/
  args:
    removes: /var/www/html/prestashop/index.php
  ignore_errors: yes

- name: Move PrestaShop hidden files (e.g., .htaccess) if any
  command: >
    sh -c 'mv /var/www/html/prestashop/.* /var/www/html/ 2>/dev/null || true'
  args:
    warn: false
  ignore_errors: yes

- name: Remove leftover prestashop directory
  file:
    path: /var/www/html/prestashop
    state: absent
  ignore_errors: yes


- name: Restart Apache after PrestaShop deployment
  service:
    name: apache2
    meta: flush_handlers
    state: restarted

